export let firstPost = [
  {
    id: 1,
    name: 'Nazwa',
    img: 'zdjecie',
    description: 'lorem',
    like: 15,
    comments: ['Pierwszwy', 'Drugi'],
    author: 'Kacper Renkel',
  },
  {
    id: 2,
    name: 'Nazwa #2',
    img: 'zdjecie',
    description:
      'Lorem Ipsum to po prostu fikcyjny tekst branży poligraficznej i składu. Lorem Ipsum jest standardowym fikcyjnym tekstem stosowanym w branży od XVI wieku, kiedy nieznany drukarz wziął kuchenkę z czcionkami i przemieszał ją, aby stworzyć wzornik czcionek. Przetrwał nie tylko pięć wieków, ale także skok w stronę składu elektronicznego, pozostając w zasadzie niezmieniony. Został spopularyzowany w latach sześćdziesiątych XX wieku wraz z wydaniem arkuszy Letraset zawierających fragmenty Lorem Ipsum, a ostatnio wraz z oprogramowaniem do publikowania na komputerach stacjonarnych, takim jak Aldus PageMaker, zawierającym wersje Lorem Ipsum.',
    like: 300,
    comments: ['Pierwszwy', 'Drugi', 'ósmy', 'komentarz'],
    author: 'Kacper Renkel',
  },
  {
    id: 3,
    name: 'Nazwa #3',
    img: 'zdjecie',
    description: 'lorem ipsum',
    like: 300,
    comments: [],
    author: 'Kacper Renkel',
  },
  {
    id: 4,
    name: 'Nazwa #4',
    img: 'zdjecie',
    description: 'lorem ipsum',
    like: 300,
    comments: [],
    author: 'Kacper Renkel',
  },
  {
    id: 5,
    name: 'Nazwa #4',
    img: 'zdjecie',
    description: 'lorem ipsum',
    like: 300,
    comments: [],
    author: 'Kacper Renkel',
  },
  {
    id: 6,
    name: 'Nazwa #4',
    img: 'zdjecie',
    description: 'lorem ipsum',
    like: 300,
    comments: [],
    author: 'Kacper Renkel',
  },
  {
    id: 7,
    name: 'Nazwa #4',
    img: 'zdjecie',
    description: 'lorem ipsum',
    like: 300,
    comments: [],
    author: 'Kacper Renkel',
  },
  {
    id: 8,
    name: 'Nazwa #4',
    img: 'zdjecie',
    description: 'lorem ipsum',
    like: 300,
    comments: [],
    author: 'Kacper Renkel',
  },
  {
    id: 9,
    name: 'Nazwa #4',
    img: 'zdjecie',
    description: 'lorem ipsum',
    like: 300,
    comments: [],
    author: 'Kacper Renkel',
  },
  {
    id: 10,
    name: 'Nazwa #4',
    img: 'zdjecie',
    description: 'lorem ipsum',
    like: 300,
    comments: [],
    author: 'Kacper Renkel',
  },
  {
    id: 11,
    name: 'Nazwa #4',
    img: 'zdjecie',
    description: 'lorem ipsum',
    like: 300,
    comments: [],
    author: 'Kacper Renkel',
  },
  {
    id: 12,
    name: 'Nazwa #4',
    img: 'zdjecie',
    description: 'lorem ipsum',
    like: 300,
    comments: [],
    author: 'Kacper Renkel',
  },
  {
    id: 13,
    name: 'Nazwa #4',
    img: 'zdjecie',
    description: 'lorem ipsum',
    like: 300,
    comments: [],
    author: 'Kacper Renkel',
  },
  {
    id: 14,
    name: 'Nazwa #4',
    img: 'zdjecie',
    description: 'lorem ipsum',
    like: 300,
    comments: [],
    author: 'Kacper Renkel',
  },
  {
    id: 15,
    name: 'Nazwa #4',
    img: 'zdjecie',
    description: 'lorem ipsum',
    like: 300,
    comments: [],
    author: 'Kacper Renkel',
  },
];
